# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Single-Cell-Fuzzy-Labels',
                'doc_host': 'https://Eamonmca.github.io',
                'git_url': 'https://github.com/Eamonmca/Single-Cell-Fuzzy-Labels',
                'lib_path': 'Single_Cell_Fuzzy_Labels'},
  'syms': {'Single_Cell_Fuzzy_Labels.core': {'Single_Cell_Fuzzy_Labels.core.foo': ('core.html#foo', 'Single_Cell_Fuzzy_Labels/core.py')}}}
